Enable Quorum Queue types for Sensor
StackStorm-Exchange/stackstorm-rabbitmq pull request #18
Opened 2022-09-20 21:37 UTC by ip-sf

This PR adds a config scheme optional key of `quorum_queues`.
When used in conjunction with a similarly named queue in `queues`, `queues_sensor.py` will now honor that by adding `arguments={"x-queue-type": "quorum"}` and performing the same as the original logic.

Other changes present look to be the result for my black/YAML linter auto fixing formatting.

I also fixed deserialization_method to actually be `required: false`, as it actually had no logic to express a default when `None` is passed.

```python
- self.deserialization_method = queue_sensor_config['deserialization_method']
+ self.deserialization_method = queue_sensor_config.get("deserialization_method", "json")
```
## Testing
I tested with various combinations of pre-existing queues and non-existing queues to test that creation/consumption behaviors still work. I also tested with mix of queues defined in `queues` and `quorum_queues` with expected results.

Then i tested a config with no key for `queues` (which failed spectacularly, as expected) as well as with `queues: []`, to which i got a graceful exit code of `0` (rather than the message `queues_sensor [-] Starting to consume messages from RabbitMQ for ['<queue name>']`)

## versioning
```bash
# rabbitmqctl version
3.10.7

# st2 --version
st2 3.7.0, on Python 3.8.10

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```

2022-09-20 21:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm-Exchange/stackstorm-rabbitmq?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm-Exchange/stackstorm-rabbitmq?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm-Exchange/stackstorm-rabbitmq?pullRequest=18) it.</sub>

2022-09-20 21:42 UTC, ip-sf commented
I would happily sign the CLA, but it opens a page with no actionable content, so i am unable to sign.

2022-09-21 10:07 UTC, armab commented
This how it shows for me: 

![image](https://user-images.githubusercontent.com/1533818/191477113-cd314886-b96f-4e9c-ad75-25a1844526bc.png)

Perhaps try a different browser.

2022-09-21 10:10 UTC, armab requested changes
Thanks for the PR and nicely composed PR description.

Please also add a `CHANGES.md` record.

2022-09-21 10:10 UTC, armab commented on pack.yaml
> +version: 1.0.1
```suggestion
version: 1.1.0
```
Let's bump the minor version for the new feature, as patch version is only for bugfixes.

2022-09-21 15:42 UTC, ip-sf commented
I realized I also missed a README update, added that in too.

2022-09-22 09:54 UTC, armab approved these changes

2022-09-22 09:54 UTC, merged

2022-09-22 10:22 UTC, armab commented
@ip-sf  Just found the pack is failing on CI after the merge.
Could you please open a follow-up PR to fix the liniting? looks like a tiny issue to fix:
https://github.com/StackStorm-Exchange/stackstorm-rabbitmq/actions/runs/3104497446/jobs/5029040997#step:6:137

2022-09-22 10:25 UTC, armab commented
Oh, I see why the CI didn't ran for this PR and I missed the status checks
![Screenshot 2022-09-22 at 11-24-12 Actions · StackStorm-Exchange_stackstorm-rabbitmq](https://user-images.githubusercontent.com/1533818/191723168-cc38fa8c-db74-4d37-8a55-922374a5ef8d.png)

cc @cognifloyd wondering what's a workaround for this as we'll probably see this in other packs.

2022-09-22 16:18 UTC, ip-sf commented
> @ip-sf Just found the pack is failing on CI after the merge. Could you please open a follow-up PR to fix the liniting? looks like a tiny issue to fix: https://github.com/StackStorm-Exchange/stackstorm-rabbitmq/actions/runs/3104497446/jobs/5029040997#step:6:137

@armab So just checking, i have no action as this is something the stackstorm team needs to fix?

I'm willing to take whatever action is required. :)

2022-09-22 21:48 UTC, armab commented
@ip-sf yeah, could you please check the linting errors here https://github.com/StackStorm-Exchange/stackstorm-rabbitmq/actions/runs/3104497446/jobs/5029040997#step:6:137 and open a PR fixing those warnings? that comes from the most recent PR and it wasn't signalized by the CI in time.